Q.1.Answer

Yes, there is a difference in data types. The list_ variable contains strings, while the array_list variable contains elements of data type numpy.str_. Here's how you can print the data types of both variables:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", type(array_list[0]))


Data type of list_: <class 'str'>
Data type of array_list: <class 'numpy.str_'>


Q.2.Answer

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
for item in list_:
    print("Data type of element in list_:", type(item))

# Print data types of elements in array_list
for item in array_list:
    print("Data type of element in array_list:", type(item))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


Q.3. Answer

Yes, there will be a difference in data types after converting array_list to integers using the dtype parameter. Here's how you can print the data types of elements in both variables:

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
for item in list_:
    print("Data type of element in list_:", type(item))

# Print data types of elements in array_list
for item in array_list:
    print("Data type of element in array_list:", type(item))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


Q.4. Answer

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape = num_array.shape

# (ii) Find the size of num_array
size = num_array.size

# Print the results
print("(i) Shape of num_array:", shape)
print("(ii) Size of num_array:", size)


(i) Shape of num_array: (2, 3)
(ii) Size of num_array: 6


Q.5. Answer

In [6]:
import numpy as np

# Create a 3x3 matrix of zeros
zeros_matrix = np.zeros((3, 3))

# Print the zeros_matrix
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q.6.Answer